# Generated by Django 6.0.5 on 2026-09-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_preorder', '0005_onlinepreorder_event_id_onlinepreorder_fbc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('STEADFAST', 'Steadfast Courier'), ('PATHAO', 'Pathao Courier'), ('REDX', 'RedX Courier'), ('CARRYBEE', 'Carrybee Courier')], max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=False, help_text='Enable or disable this delivery agent in online preorders')),
                ('is_default', models.BooleanField(default=False, help_text='Default selected courier agent')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('base_url', models.CharField(blank=True, max_length=255, null=True)),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('store_id', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Courier Setting',
                'verbose_name_plural': 'Courier Settings',
                'ordering': ['provider'],
            },
        ),
        migrations.AddField(
            model_name='onlinepreorder',
            name='courier_consignment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onlinepreorder',
            name='courier_dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlinepreorder',
            name='courier_partner',
            field=models.CharField(blank=True, help_text='STEADFAST, PATHAO, REDX, CARRYBEE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onlinepreorder',
            name='courier_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlinepreorder',
            name='courier_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onlinepreorder',
            name='courier_tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
