# Generated by Django 6.0.5 on 2026-09-14 01:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('online_preorder', '0006_couriersetting_onlinepreorder_courier_consignment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinepreorder',
            name='hold_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='onlinepreorder',
            name='is_stock_restored',
            field=models.BooleanField(default=False, help_text='Whether items in this returned order have been restocked to inventory'),
        ),
        migrations.AddField(
            model_name='onlinepreorder',
            name='return_charge_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Delivery charge amount counted when store bears return fee', max_digits=10),
        ),
        migrations.AddField(
            model_name='onlinepreorder',
            name='return_delivery_charge_paid_by_customer',
            field=models.BooleanField(default=True, help_text='True if customer paid return delivery fee, False if store bears cost'),
        ),
        migrations.AddField(
            model_name='onlinepreorder',
            name='return_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_preorders', to='expenses.expense'),
        ),
        migrations.AddField(
            model_name='onlinepreorder',
            name='return_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='onlinepreorder',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onlinepreorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('HOLD', 'Hold'), ('RETURNED', 'Returned')], default='PENDING', max_length=12),
        ),
    ]
