# Generated by Django 6.0.5 on 2026-09-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_preorder', '0007_onlinepreorder_hold_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinepreorder',
            name='is_stock_deducted',
            field=models.BooleanField(default=False, help_text='Whether items in this preorder have had stock deducted from inventory'),
        ),
        migrations.AlterField(
            model_name='onlinepreorder',
            name='is_stock_restored',
            field=models.BooleanField(default=False, help_text='Whether items in this returned or cancelled order have been restocked to inventory'),
        ),
    ]
