# Generated by Django 6.0.5 on 2026-09-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_preorder', '0008_onlinepreorder_is_stock_deducted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinepreorder',
            name='courier_delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
