# Generated by Django 6.0.5 on 2026-09-18 12:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_sale_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='delivery_charge_paid_by_customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='return',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='return',
            name='refund_method',
            field=models.CharField(blank=True, default='cash', max_length=50),
        ),
        migrations.AddField(
            model_name='return',
            name='return_charge_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='return',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='completed', max_length=20),
        ),
    ]
