# Generated by Django 6.0.5 on 2026-09-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_return_delivery_charge_paid_by_customer_return_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True, unique=True),
        ),
    ]
